events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blank/', views.blankPage, name="blank"),
    path('', views.eventsPage, name="events"),
    path('about/', views.aboutPage, name="about"),
    path('event/<str:pk>/', views.singleEvent, name="single-event"),
    path('add-event/', views.addEvent, name="add-event"),
    path('update-event/<str:pk>/', views.updateEvent, name="update-event"),
    path('delete-event/<str:pk>/', views.deleteEvent, name="delete-event"),
    path('tickets/', views.ticketPage, name="tickets"),
    path('add-tickets/', views.addTicket, name="add-ticket"),
    # # path('update-event/<str:pk>/', views.updateTicket, name="update-ticket"),
    path('delete-ticket/<str:pk>/', views.deleteTicket, name="delete-ticket"),
    
    path('passes/', views.passesPage, name="passes"),
    path('add-member/', views.addTeamMembers, name="add-member"),
    path('update-member/<str:pk>/', views.updateTeamMembers, name="update-member"),
    path('delete-member/<str:pk>/', views.deleteTeamMember, name="delete-member"),
    
    path('add-pass/', views.addMemberPass, name="add-member-pass"),
    path('delete-pass/<str:pk>/', views.deleteMemberPass, name="delete-member-pass"),
    
]

floak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('', include('users.urls')),
    path('', include('users.auth_urls')),
    path('', include('checkouts.urls')),
    path('', include('scan.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scan/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('scan/', views.scan_view, name='scan_view'),
    path('scan_checking.../', views.qr_code_handler, name='qr_code_handler'),
    path('scan-success/', views.scan_success, name='scan_success'),
    path('scan-failed/', views.failurePage, name='scan-failed'),
]

events/models.py
from django.db import models
import uuid
from users.models import Profile, TeamMember
from django.db import models
from django.conf import settings
from django.utils import timezone
import qrcode
import io
from django.core.files.base import ContentFile
import uuid
from io import BytesIO
from users.models import Profile

class Event(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default='events/default.JPG', upload_to='events/')
    date_time = models.DateTimeField(null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


#we can get the this also as a member passes
class TicketLevel(models.Model):
    # STATUS_CHOICES = [
    #     (1, 'Default Pass'),
    #     (2, 'Member Pass'),

    # ]
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    created = models.DateTimeField(default=timezone.now)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    # status = models.IntegerField(choices=STATUS_CHOICES, default=1)

    def __str__(self):
        return f"{self.name} for {self.event}"


import uuid

def generate_uuid4():
    return str(uuid.uuid4())


def qr_code_upload_path(instance, filename):
    # Generates the upload path: qr_codes/ticket_level/<filename>
    return f'qr_codes/{instance.ticket_level}/{filename}'
class Ticket(models.Model): 
    STATUS_CHOICES = [
        (1, 'Available'),
        (2, 'Assigned'),
        (3, 'Used')
    ]

    
    ticket_level = models.ForeignKey(TicketLevel, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    qr_code = models.ImageField(upload_to=qr_code_upload_path, blank=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    id = models.UUIDField(default=generate_uuid4, unique=True, primary_key=True, editable=False)
    
    def save(self, *args, **kwargs):
        if not self.qr_code:
            self.generate_qr_code()
        super().save(*args, **kwargs)

    def generate_qr_code(self):
        qr_data = f"Ticket ID: {self.id}, Ticket Level: {self.ticket_level}, Event: {self.ticket_level.event}, Price: {self.ticket_level.price}"
        qr = qrcode.make(qr_data)
        buffer = BytesIO()
        qr.save(buffer, format='PNG')
        file_name = f"qr_code_{self.id}.png"
        self.qr_code.save(file_name, ContentFile(buffer.getvalue()), save=False)

    def __str__(self):
        return str(self.id)
    
    

class MemberPass(models.Model):

    owner = models.ForeignKey(TeamMember, null=True, blank=True, on_delete=models.SET_NULL)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    quantity = models.PositiveIntegerField()
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.owner)
    
    

    

def pass_qr_code_upload_path(instance, filename):
    # Generates the upload path: qr_codes/ticket_level/<filename>
    return f'qr_codes/{instance._pass}/{filename}'

class Pass(models.Model): 
    # STATUS_CHOICES = [
    #     (1, 'Available'),
    #     (2, 'Assigned'),
    #     (3, 'Used')
    # ]

    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    _pass = models.ForeignKey('MemberPass', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    qr_code = models.ImageField(upload_to=pass_qr_code_upload_path, blank=True)
    # status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    
    def save(self, *args, **kwargs):
        if not self.qr_code:
            self.generate_qr_code()
        super().save(*args, **kwargs)

    def generate_qr_code(self):
        qr_data = f"Ticket ID: {self.id}, pass: {self._pass.id}"
        qr = qrcode.make(qr_data)
        buffer = BytesIO()
        qr.save(buffer, format='PNG')
        file_name = f"qr_code_{self.id}.png"
        self.qr_code.save(file_name, ContentFile(buffer.getvalue()), save=False)

    def __str__(self):
        return str(self.id)

events/forms.py
from urllib import request
from django.forms import ModelForm
from django import forms

from .models import Event, TicketLevel, MemberPass
from users.models import TeamMember

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'featured_image', 'date_time', 'location']
        
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        
        self.fields['title'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
        self.fields['description'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
        self.fields['featured_image'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
        self.fields['date_time'].widget.attrs.update(
            {'class': 'form-control', 'id': 'datetime-picker'}
        )
        
        self.fields['location'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
class TicketLevelForm(ModelForm):
    class Meta:
        model = TicketLevel
        fields = ['name', 'price', 'quantity']
        
    def __init__(self, *args, **kwargs):
        super(TicketLevelForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
        self.fields['price'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
        self.fields['quantity'].widget.attrs.update(
            {'class': 'form-control'}
        )

class TeamMemberForm(ModelForm):
    class Meta:
        model = TeamMember
        fields = ['name', 'email', 'idn']
        
    def __init__(self, *args, **kwargs):
        super(TeamMemberForm, self).__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
        self.fields['idn'].widget.attrs.update(
            {'class': 'form-control'}
        )
        
class MemberPassForm(ModelForm):
    class Meta:
        model = MemberPass
        fields = ['quantity']
        
    def __init__(self, *args, **kwargs):
        super(MemberPassForm, self).__init__(*args, **kwargs)

        self.fields['quantity'].widget.attrs.update(
            {'class': 'form-control'}
        )

events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Event
from .utils import searchEvents
from .forms import EventForm, TicketLevelForm, TeamMemberForm, MemberPassForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from users.models import Profile, TeamMember
from .models import TicketLevel , MemberPass


def blankPage(request):
    page = "blank"
    context = {'page': page}
    return render(request, 'events/blank.html', context)

def eventsPage(request):
    events, search_query = searchEvents(request)
    page = "events"
    context = {'page': page, 'events': events, 'search_query': search_query}
    return render(request, 'events/events.html', context)

def aboutPage(request):
    page = "about"
    context = {'page': page}
    return render(request, 'events/about.html', context)

def singleEvent(request, pk):
    page = "single-event"
    event = get_object_or_404(Event, id=pk)
    ticket_levels = TicketLevel.objects.filter(event=pk)
    context = {'page': page, 'event': event, 'ticket_levels':ticket_levels}
    return render(request, 'events/single-event.html', context)

@login_required(login_url="login")
def addEvent(request):
    page = 'add-event'
    profile = request.user.profile
    form = EventForm()
    
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.owner = profile
            event.save()
            messages.success(request, 'Event added successfully!')
            return redirect('admin')

    context = {'page': page, 'form': form}
    return render(request, 'events/add-event.html', context)

@login_required(login_url="login")
def updateEvent(request, pk):
    page = 'update-event'
    profile = request.user.profile
    event = get_object_or_404(profile.event_set, id=pk)
    form = EventForm(instance=event)
    
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES, instance=event)
        if form.is_valid():
            form.save()
            messages.success(request, 'Event updated successfully!')
            return redirect('admin')

    context = {'page': page, 'form': form}
    return render(request, 'events/update-event.html', context)

@login_required(login_url="login")
def deleteEvent(request, pk):
    page = 'delete-event'
    event = get_object_or_404(Event, id=pk)
    
    if request.method == 'POST':
        event.delete()
        messages.success(request, 'Event deleted successfully!')
        return redirect('admin')

    context = {'page': page, 'event': event}
    return render(request, 'events/delete-event.html', context)

@login_required(login_url="login")
def ticketPage(request):
    page = 'tickets'
    profile = request.user.profile
    ticket_levels = TicketLevel.objects.filter(owner=profile)
    context = {'page': page, 'ticket_levels': ticket_levels}
    return render(request, 'events/tickets.html', context)


@login_required(login_url="login")
def passesPage(request):
    page = 'passes'
    profile = request.user.profile
    team_members = TeamMember.objects.filter(organizer=profile)
    context = {'page': page, 'team_members':team_members}
    return render(request, 'events/passes.html', context)


@login_required(login_url="login")
def addTicket(request):
    page = 'add-ticket'
    profile = request.user.profile
    events = Event.objects.filter(owner=profile)
    profile = request.user.profile
    
    form = TicketLevelForm() 
    if request.method == 'POST':
        form = TicketLevelForm(request.POST)
        event = request.POST.get('event')
        event = Event.objects.get(id=event)
        if form.is_valid():
            ticket_level = form.save(commit=False)
            ticket_level.owner = profile
            ticket_level.event = event
            ticket_level.save()
            messages.success(request, 'Ticket added successfully!')
            return redirect('tickets')

    context = {'page': page, 'form': form, 'events':events}
    return render(request, 'events/add-ticket.html', context)


@login_required(login_url="login")
def addTeamMembers(request):
    page = 'add-team-member'
    profile = request.user.profile

    form = TeamMemberForm() 
    if request.method == 'POST':
        form = TeamMemberForm(request.POST)
        if form.is_valid():
            team_member = form.save(commit=False)
            team_member.organizer = profile
            team_member.save()
            messages.success(request, 'Member added successfully!')
            return redirect('passes')

    context = {'page': page, 'form': form}
    return render(request, 'events/add-member.html', context)

@login_required(login_url="login")
def updateTeamMembers(request, pk):
    page = 'update-team-member'
    profile = request.user.profile
    member=TeamMember.objects.get(id=pk)

    form = TeamMemberForm(instance=member) 
    if request.method == 'POST':
        form = TeamMemberForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            messages.success(request, 'Member updates successfully!')
            return redirect('passes')

    context = {'page': page, 'form': form}
    return render(request, 'events/update-member.html', context)

@login_required(login_url="login")
def deleteTeamMember(request, pk):
    page = 'delete-team-member'
    member=TeamMember.objects.get(id=pk)
    
    if request.method == 'POST':
        member.delete()
        messages.success(request, 'Member deleted successfully!')
        return redirect('passes')

    context = {'page': page, 'member': member}
    return render(request, 'events/delete-member.html', context)

# @login_required(login_url="login")
# def updateTicket(request, pk):
#     page = 'update-ticket'
#     profile = request.user.profile
#     ticket = get_object_or_404(TicketPrice, id=pk)
#     form = TicketForm(instance=ticket)
    
#     if request.method == 'POST':
#         form = TicketForm(request.POST, instance=ticket)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Ticket updated successfully!')
#             return redirect('tickets')

#     context = {'page': page, 'form': form}
#     return render(request, 'events/update-ticket.html', context)


@login_required(login_url="login")
def deleteTicket(request, pk):
    page = 'delete-ticket'
    ticket = get_object_or_404(TicketLevel, id=pk)
    
    if request.method == 'POST':
        ticket.delete()
        messages.success(request, 'Tickets deleted successfully!')
        return redirect('tickets')

    context = {'page': page, 'ticket': ticket}
    return render(request, 'events/delete-ticket.html', context)


@login_required(login_url="login")
def deleteMemberPass(request, pk):
    page = 'delete-member-pass'
    member_pass = get_object_or_404(MemberPass, id=pk)
    
    if request.method == 'POST':
        member_pass.delete()
        messages.success(request, 'Passes deleted successfully!')
        return redirect('passes')

    context = {'page': page, 'member_pass': member_pass}
    return render(request, 'events/delete-member-pass.html', context)


@login_required(login_url="login")
def addMemberPass(request):
    page = 'add-member-pass'
    profile = request.user.profile

    team_members = TeamMember.objects.filter(organizer=profile)

    form = MemberPassForm() 
    if request.method == 'POST':
        form = MemberPassForm(request.POST)
        member = request.POST.get('member')
        if form.is_valid():
            member_pass = form.save(commit=False)
            member = TeamMember.objects.get(id=member)
            member_pass.owner = member
            member_pass.save()
            messages.success(request, 'Member pass added successfully!')
            return redirect('passes')

    context = {'page': page, 'form': form, 'team_members':team_members}
    return render(request, 'events/add-pass.html', context)

events/templates/events/about.html
{% extends 'ui-2/main.html' %}

{% load static %}

{% block content %}

      <!-- ============================================-->
      <!-- <section> begin ============================-->
      <section class="bg-dark text-center py-9">
        <div class="container">
          <p class="text-light fs-1">About</p>
          <div class="col-12 col-md-7 mx-auto">
            <h1 class="text-white fs-lg-7 fs-md-4 fs-3 my-4">We love to make great things, things that get life better.</h1>
          </div>
          <p class="w-md-50 text-light mx-auto">BUY - SCAN - ENJOY</p>
        </div><!-- end of .container-->
      </section><!-- <section> close ============================-->
      <!-- ============================================-->



      <!-- ============================================-->
      <!-- <section> begin ============================-->
      <section class="pb-0">
        <div class="container">
          <div class="gallery-wraper">
            <div class="img-wraper"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/gallery/1.png' %}" alt="" /></div>
            <div class="img-wraper"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/gallery/2.png' %}" alt="" /></div>
            <div class="img-wraper"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/gallery/3.png' %}" alt="" /></div>
            <div class="img-wraper"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/gallery/4.png' %}" alt="" /></div>
            <div class="img-wraper"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/gallery/5.png' %}" alt="" /></div>
          </div>
          <div class="px-xl-8 px-md-5 px-3 py-8">
            <p class="fs-1">Our Makeup</p>
            <h1 class="fs-lg-6 fs-md-4 fs-3 my-4">EventEaze: Streamlined Ticketing for Unforgettable Experiences.</h1>
            <p class="fs-1">EventEaze offers a sophisticated yet user-friendly ticketing system designed to simplify event management. From seamless booking processes to personalized attendee experiences, EventEaze ensures every event is memorable and hassle-free.</p>
          </div>
        </div><!-- end of .container-->
      </section><!-- <section> close ============================-->
      <!-- ============================================-->



      <!-- ============================================-->
      <!-- <section> begin ============================-->
      <!-- <section class="bg-dark">
        <div class="container">
          <p class="text-center text-light">Our numbers</p>
          <h1 class="text-center text-white w-lg-75 mx-auto fs-xl-6 fs-lg-4 fs-3">Handshake infographic mass market crowdfunding iteration.</h1>
          <div class="row mt-5">
            <div class="col-md-4 col-sm-6 text-center">
              <h1 class="text-success fs-5 fs-md-6 fs-lg-7 fs-xl-9">120M</h1>
              <p class="text-light fs-2">Cool feature title</p>
            </div>
            <div class="col-md-4 col-sm-6 text-center">
              <h1 class="text-success fs-5 fs-md-6 fs-lg-7 fs-xl-9">10.000</h1>
              <p class="text-light fs-2">Cool feature title</p>
            </div>
            <div class="col-md-4 col-sm-6 text-center">
              <h1 class="text-success fs-5 fs-md-6 fs-lg-7 fs-xl-9">240</h1>
              <p class="text-light fs-2">Cool feature title</p>
            </div>
          </div>
        </div>
      </section> -->
      <!-- ============================================-->



      <!-- ============================================-->
      <!-- <section> begin ============================-->
      <!-- <section>
        <div class="container">
          <div class="px-xl-8 px-md-5 px-3">
            <p class="text-gray fs-1">Our team</p>
            <h1 class="text-black fs-lg-6 fs-md-4 fs-3 my-4">The leadership team</h1>
            <p class="text-gray fs-1 w-lg-75">Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration. Traction stock user experience deployment beta innovator incubator focus.</p>
          </div>
          <div class="row mt-7">
            <div class="col-md-4 col-sm-6 mb-5 mb-lg-0 text-center text-sm-left"><a href="#"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/team/1.png' %}" alt="" /></a>
              <h1 class="fs-3 mt-3">Michael Scott</h1>
              <p class="fs-1">General Manager</p>
            </div>
            <div class="col-md-4 col-sm-6 mb-5 mb-lg-0 text-center text-sm-left"><a href="#"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/team/2.png' %}" alt="" /></a>
              <h1 class="fs-3 mt-3">Dwight Schrute</h1>
              <p class="fs-1">General Manager</p>
            </div>
            <div class="col-md-4 col-sm-6 mb-5 mb-lg-0 text-center text-sm-left"><a href="#"><img class="img-fluid" src="{% static '' %}ui-kit-2/build/assets/img/team/3.png" alt="" /></a>
              <h1 class="fs-3 mt-3">Pam Beetsley</h1>
              <p class="fs-1">General Manager</p>
            </div>
          </div>
        </div>
      </section> -->
      <!-- ============================================-->



      <!-- ============================================-->
      <!-- <section> begin ============================-->
      <!-- <section class="bg-dark">
        <div class="container">
          <div class="px-xl-8 px-md-5 px-3">
            <p class="text-light fs-1">Our values</p>
            <h1 class="text-white fs-lg-6 fs-md-4 fs-3 my-lg-4 my-3">Things in we believe</h1>
            <p class="text-light w-lg-75 fs-1">Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration. Traction stock user experience deployment beta innovator incubator focus.</p>
            <div class="row mt-5">
              <div class="col-md-3"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/values/1.png' %}" alt="" /></div>
              <div class="col-md-9 mt-2 mb-md-0">
                <h1 class="text-white fs-2 fs-lg-3 my-2">We are commited.</h1>
                <p class="text-light fs-1">Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration.</p>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col-md-3"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/values/2.png' %}" alt="" /></div>
              <div class="col-md-9 mt-2 mb-md-0">
                <h1 class="text-white fs-2 fs-lg-3 my-2">We are responsible.</h1>
                <p class="text-light fs-1">Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration.</p>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col-md-3"><img class="img-fluid" src="{% static 'ui-kit-2/build/assets/img/values/3.png' %}" alt="" /></div>
              <div class="col-md-9 mt-2 mb-md-0">
                <h1 class="text-white fs-2 fs-lg-3 my-2">We aim for progress.</h1>
                <p class="text-light fs-1">Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration.</p>
              </div>
            </div>
          </div>
        </div>
      </section> -->

    </main><!-- ===============================================-->
    <!--    End of Main Content-->
    <!-- ===============================================-->



    <!-- ============================================-->
    <!-- <section> begin ============================-->
    <section>
      <div class="container bg-dark overflow-hidden rounded-1">
        <div class="bg-holder" style="background-image: url('ui-kit-2/build/assets/img/promo/promo-bg.png');"></div>
        <!--/.bg-holder-->
        <div class="px-5 py-7 position-relative">
          <h1 class="text-center w-lg-75 mx-auto fs-lg-6 fs-md-4 fs-3 text-white">Want to have a meetup? Let's do it!</h1>
          <div class="row justify-content-center mt-5">
            <div class="col-auto w-100 w-lg-50"><input class="form-control mb-2 border-light fs-1" type="email" placeholder="Your email address" /></div>
            <div class="col-auto mt-2 mt-lg-0"><button class="btn btn-success text-dark fs-1">Say Hello!</button></div>
          </div>
        </div>
      </div><!-- end of .container-->
    </section><!-- <section> close ============================-->
    <!-- ============================================-->




    {% endblock content %}

events/templates/events/passes.html
{% extends 'ui/main.html' %}

{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-6 col-md-12 mb-4">
            <div class="row justify-content-end">
                <div class="col-auto mt-3 mb-3">
                  <a href="{% url 'add-member' %}" type="submit" class="btn btn-primary">Add</a>
                </div>
              </div>
            <!-- Basic Bootstrap Table -->
            <div class="card">
                <div class="row">
                    <div class="col-10">
                        <h5 class="card-header">Team Members</h5>
                    </div>
                    
                </div>

                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>ID Number</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            {% for team_member in team_members %}
                            <tr>
                                <td><strong>{{ team_member.name }}</strong></td>
                                <td>{{ team_member.idn }}</td>
                                <td>
                                    <div class="dropdown">
                                        <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                            <i class="bx bx-dots-vertical-rounded"></i>
                                        </button>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" href="{% url 'update-member' team_member.id %}">
                                                <i class="bx bx-edit me-1"></i> Edit
                                            </a>
                                            <a class="dropdown-item" href="{% url 'delete-member' team_member.id %}">
                                                <i class="bx bx-trash me-1"></i> Delete
                                            </a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <!--/ Basic Bootstrap Table -->
        </div>

        <div class="col-lg-6 col-md-12 mb-4">
            <div class="row justify-content-end">
                <div class="col-auto mt-3 mb-3">
                  <a href="{% url 'add-member-pass' %}" type="submit" class="btn btn-primary">Add</a>
                </div>
              </div>
            <!-- Basic Bootstrap Table -->
            <div class="card">
                <div class="row">
                    <div class="col-10">
                        <h5 class="card-header">Member Passes</h5>
                    </div>
                    
                </div>

                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Quantity</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            {% for team_member in team_members %}
                                {% for pass in team_member.memberpass_set.all %}
                                <tr>
                                    <td><strong>{{ team_member.name }}</strong></td>
                                    <td>{{ pass.quantity }}</td>
                                    <td>
                                        <div class="dropdown">
                                            <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                                <i class="bx bx-dots-vertical-rounded"></i>
                                            </button>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" href="{% url 'delete-member-pass' pass.id %}">
                                                    <i class="bx bx-trash me-1"></i> Delete
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
            <!--/ Basic Bootstrap Table -->
        </div>
    </div>
</div>
{% endblock content %}